import Sidebar from "./Sidebar"
import { Inter } from "next/font/google";
import "../../globals.css";
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  const inter = Inter({ subsets: ["latin"] });

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body style={{ display : 'flex'}} className={`${inter.className} antialiased max-w-screen`}>
            <Sidebar />
            {children}
            </body>
      </html>
    )
  }
  